//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingeniero_especialidad
    {
        public int cedula_ingeniero { get; set; }
        public string nombre_especialidad { get; set; }
        public short id_ingesp { get; set; }
    
        public virtual especialidad especialidad { get; set; }
        public virtual ingeniero ingeniero { get; set; }
    }
}
