//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public int cedula { get; set; }
        public string nombre { get; set; }
        public int telefono { get; set; }
        public Nullable<int> horasproyecto { get; set; }
        public Nullable<int> pagohora { get; set; }
        public string nombre_proyecto { get; set; }
    
        public virtual proyecto proyecto { get; set; }
    }
}
