/*SE EJECUTA PRIMERO*/
CREATE DATABASE TEConstruye
/*CREAR UN QUERY DESDE LA BASE DE DATOS ANTES CREADA*/
CREATE TABLE EMPLEADO(
	Cedula INT PRIMARY KEY NOT NULL,
	Nombre VARCHAR(50) NOT NULL,
	Apellido VARCHAR(50) NOT NULL,
	Telefono INT NOT NULL,
	HorasProyecto INT,
	PagoHora INT,
	Nombre_Proyecto VARCHAR(50) NOT NULL);
CREATE TABLE PROYECTO(
	Nombre VARCHAR(50) PRIMARY KEY NOT NULL,
	Proveedor VARCHAR(50),
	Numero_Factura INT NOT NULL
	--MaterialesComprados VARCHAR(50)
	);
CREATE TABLE FACTURA(
	Numero INT PRIMARY KEY NOT NULL,
	FotoFactura VARCHAR(100)
	);
CREATE TABLE INGENIERO(
	Cedula INT PRIMARY KEY NOT NULL,
	Telefono INT NOT NULL,
	Nombre VARCHAR(50) NOT NULL,
	Apellido VARCHAR(50) NOT NULL,
	Codigo INT NOT NULL,
	Nombre_Proyecto VARCHAR(50) NOT NULL
);
CREATE TABLE ESPECIALIDAD(
	Nombre VARCHAR(50) PRIMARY KEY NOT NULL
);
CREATE TABLE OBRA(
	Nombre VARCHAR(50) PRIMARY KEY NOT NULL,
	Ubicacion VARCHAR(50) NOT NULL,
	MetCuadLote INT NOT NULL,
	MetCuadConst INT NOT NULL,
	Pisos INT NOT NULL,
	Baños INT,
	CantHabit INT,
	Nombre_Proyecto VARCHAR(50) NOT NULL
	--Materiales VARCHAR(50)/*CREO que esta deberia obtenerse por un select y no como atributo*/
);
CREATE TABLE ETAPA_DEFAULT(
	NombreEtapa VARCHAR(50) PRIMARY KEY NOT NULL,
	Descripcion VARCHAR(500) NOT NULL
);
CREATE TABLE ETAPA(
	Nombre VARCHAR(50) PRIMARY KEY NOT NULL,
	Presupuesto INT NOT NULL,
	FechaInicio DATE NOT NULL,
	FechaFin DATE NOT NULL,
	Costo INT,
	Codigo_Material INT NOT NULL
);

CREATE TABLE MATERIAL(
	Codigo INT PRIMARY KEY NOT NULL,
	Nombre VARCHAR(50) NOT NULL,
	Proveedor VARCHAR(50) NOT NULL,
	PrecioUnitario INT NOT NULL
);

CREATE TABLE CLIENTE(
	Cedula INT PRIMARY KEY NOT NULL,
	Nombre VARCHAR(50) NOT NULL,
	Apellido VARCHAR(50) NOT NULL,
	Telefono INT NOT NULL
);

CREATE TABLE INGENIERO_ESPECIALIDAD(
	Cedula_Ingeniero INT NOT NULL,
	Nombre_Especialidad VARCHAR(50) NOT NULL,
	PRIMARY KEY(Cedula_Ingeniero,Nombre_Especialidad)
);

CREATE TABLE ETAPA_OBRA(
	Nombre_Etapa VARCHAR(50) NOT NULL,
	Nombre_Obra VARCHAR(50) NOT NULL,
	PRIMARY KEY(Nombre_Etapa,Nombre_Obra)
);


ALTER TABLE EMPLEADO ADD CONSTRAINT FK_EMPLEADO_PROYECTO FOREIGN KEY (Nombre_Proyecto) REFERENCES PROYECTO(Nombre);
ALTER TABLE PROYECTO ADD CONSTRAINT FK_PROYECTO_FACTURA FOREIGN KEY (Numero_Factura) REFERENCES FACTURA(Numero);
ALTER TABLE INGENIERO ADD CONSTRAINT FK_INGENIERO_PROYECTO FOREIGN KEY (Nombre_Proyecto) REFERENCES PROYECTO(Nombre);
ALTER TABLE OBRA ADD CONSTRAINT FK_OBRA_PROYECTO FOREIGN KEY (Nombre_Proyecto) REFERENCES PROYECTO(Nombre);
ALTER TABLE ETAPA ADD CONSTRAINT FK_ETAPA_ETAPA_DEFAULT FOREIGN KEY (Nombre) REFERENCES ETAPA_DEFAULT(NombreEtapa);
ALTER TABLE ETAPA ADD CONSTRAINT FK_ETAPA_MATERIAL FOREIGN KEY (Codigo_Material) REFERENCES MATERIAL(Codigo);

ALTER TABLE INGENIERO_ESPECIALIDAD ADD CONSTRAINT FK_INGENIEROESPECIALIDAD_INGENIERO FOREIGN KEY (Cedula_Ingeniero)
REFERENCES INGENIERO(Cedula);
ALTER TABLE INGENIERO_ESPECIALIDAD ADD CONSTRAINT FK_INGENIEROESPECIALIDAD_ESPECIALIDAD FOREIGN KEY (Nombre_Especialidad)
REFERENCES ESPECIALIDAD(Nombre);

ALTER TABLE ETAPA_OBRA ADD CONSTRAINT FK_ETAPAOBRA_ETAPA FOREIGN KEY (Nombre_Etapa)
REFERENCES ETAPA(Nombre);
ALTER TABLE ETAPA_OBRA ADD CONSTRAINT FK_ETAPAOBRA_OBRA FOREIGN KEY (Nombre_Obra)
REFERENCES OBRA(Nombre);